[package]
name = "see"
version = "0.0.1"
edition = "2018"

authors = ["wyhaya <wyhaya@gmail.com>"]
description = "Static HTTP file server"
homepage = "https://github.com/wyhaya/see"
repository = "https://github.com/wyhaya/see.git"
license = "MIT"
readme = "README.md"

keywords = [
    "http",
    "static",
    "web",
    "server"
]

[dependencies]
ace = "0.2.0"
async-compression = { version = "0.2.0", features = ["futures-write", "gzip", "deflate", "brotli"] }
bright = "0.3.0"
dirs = "2.0.2"
futures = "0.3.4"
globset = "0.4.5"
hyper = "0.13.4"
lazy_static = "1.4.0"
rand = "0.7.3"
regex = "1.3.6"
time = "0.1.42"
tokio = { version = "0.2.16", features = ["full"] }
tokio-rustls = "0.13.0"
webpki-roots = "0.19.0"
yaml-rust = "0.4.3"

[target.'cfg(unix)'.dependencies]
libc = "0.2.68"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["processthreadsapi"] }