[package]
name = "see"
version = "0.0.1"
edition = "2018"

authors = ["wyhaya <wyhaya@gmail.com>"]
description = "Static HTTP file server"
homepage = "https://github.com/wyhaya/see"
repository = "https://github.com/wyhaya/see.git"
license = "MIT"
readme = "README.md"

keywords = [
    "http",
    "static",
    "web",
    "server"
]

[dependencies]
ace = "0.0.3"
async-compression = {version = "0.2.0", features = ["futures-write","gzip", "deflate", "brotli"] }
base64 = "0.11.0"
bright = "0.2.0"
chrono = "0.4.10"
dirs = "2.0.2"
futures = "0.3.1"
globset = "0.4.4"
hyper = "0.13.1"
hyper-tls = "0.4.0"
lazy_static = "1.4.0"
libc = "0.2.66"
rand = "0.7.2"
regex = "1.3.1"
tokio = { version = "0.2.4", features = ["full"] }
tokio-rustls = "0.12.1"
yaml-rust = "0.4.3"